### ISSUE TITLE
Incorrect Auth0 URI

### ISSUE THREAD

**Issue by sheathompson** [expresstechsoftware/connect-gamipress-discord-addon#26]
First off, I think your plugin was hacked - your documentation page takes me to a SCAM sales website.

Second, I would please like the step-by-step guide. I've followed everything in your photos and nothing works. Won't verify the AUTH0 when trying to link into the server with my bot. But I copy and pasted the two URI links you have there directly into my bot. MY bot has administrator rank, so it should work. Please help

**Comment by ravisoni6262** [comment]
@younes-dro We have guide ready? Also can we verify scam sales page?

**Comment by younes-dro** [comment]
@ravisoni6262 @sheathompson 
yes the page is published : 
https://www.expresstechsoftwares.com/connect-gamipress-and-discord/

Please pay attention to the section : Create a new application inside disocrd.com

**Comment by younes-dro** [comment]
@sheathompson 
the two links in the Tab documentation point to : expresstechsoftwares website. NO SCAM

**Comment by sheathompson** [comment]
Okay awesome thank you! Your plugin refers only directly to this page https://www.expresstechsoftwares.com not to the one you just linked that's why I was confused sorry. You should include it somewhere a little easier to get to, I think your plugin is brilliant! IF I can get it to work haha. I'll let you know how it goes, I tried everything last time and keep getting an Auth0 error. Do you have any suggestions?

Thank you for your prompt response

**Comment by sheathompson** [comment]
Okay, a few things if you could help me @younes-dro 

1. I got the plugin to work, it shows all the content the way I would expect, but nothing changes. It does not grant me the role I am in gamipress in Discord
2. Is your plugin also supposed to add me to the discord server? This doesn't happen automatically. I have to manually join with a separate link right now first, then use your plugin. But it doesn't change my role for some reason. If its possible I can just use your one link from the plugin to join the server, AND get the role - that would solve a major problem for me.

Please any insight you can give me would be super helpful

**Comment by younes-dro** [comment]
@sheathompson 
 If you successfully connected the Bot AND you gave it the highest priority, then you have done what is necessary.
 
 the next step: map roles to GamiPress Ranks :

 
 
![discord-roles-gamipress-ranks-768x640](https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/31171/f0fecad9-1858-4b1f-ae36-b74c0c5ae150)

and that's all ! each time a user has a Rank, he will have the role linked to the Rank.

each user will be able to access your discord server via their profile page : 
![connect-gamipress-users-discord-roles-768x306](https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/31171/53c2bd06-7c45-41b2-9111-a829bc893586)

**Comment by sheathompson** [comment]
I've double checked all my settings, and nothing happens for some reason. When I use the link on a test discord account, it brings me to that approve screen from discord, but doesn't join me to the server, nor does it give me the role I asked for. I posted screenshots of all my settings below, please let me know if I did anything wrong.

I'm also seeing this in your plugin's log records

 2023-11-10 15:20:21==>File:/home/scientif/skye-collective.com/wp-content/plugins/connect-gamipress-and-discord/public/class-connect-gamipress-discord-addon-public.php::User Id:53::Line:582::Function:ets_gamipress_discord_create_member_dm_channel::50035:Invalid Form Body 

<img width="665" alt="Screenshot 2023-12-30 185937" src="https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/42765461/8b86e9a4-5c43-4635-bb29-cbd81f9e799e">
<img width="381" alt="Screenshot 2023-12-30 185915" src="https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/42765461/432542ba-6388-4dc4-a3e1-316d53879e0a">
<img width="845" alt="Screenshot 2023-12-30 185303" src="https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/42765461/768d6e74-43e1-4db4-b498-1ad585ee2029">
<img width="243" alt="Screenshot 2023-12-30 152922" src="https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/42765461/81c41de7-0ed0-4a24-b5df-100e20ce488c">
<img width="772" alt="Screenshot 2023-12-30 190018" src="https://github.com/expresstechsoftware/connect-gamipress-discord-addon/assets/42765461/5bd5632e-952a-4a2e-b5be-a98c53e1034b">

**Comment by younes-dro** [comment]
@sheathompson 
The Invalid Form Body Error occurs when : Required Fields ara missing
can you give me the link to test an account?
